name: open_split
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  cloud_firestore: ^6.1.2
  connectivity_plus: ^7.0.0
  dartz: ^0.10.1
  drift: ^2.31.0
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  firebase_storage: ^13.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  go_router: ^17.1.0
  injectable: ^2.7.1+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  build_runner: ^2.11.1
  injectable_generator: ^2.9.1
  drift_dev: ^2.31.0

flutter:
  uses-material-design: true
